name: 'GitHub Content Moderator'
description: 'Moderates content in issues, PRs, and comments using the OpenAI API.'
inputs:
  github-token:
    description: 'The GitHub token.'
    required: true
    default: '${{ github.token }}'
  openai-api-key:
    description: 'The OpenAI API key. If not provided, the `github-token` will be used to authenticate with the GitHub Copilot API.'
    required: false
    default: ''
  openai-endpoint:
    description: 'The OpenAI API endpoint.'
    required: false
    default: 'https://models.github.ai/inference'
  openai-model:
    description: 'The OpenAI model to use.'
    required: false
    default: 'openai/gpt-4.1-mini'
  text-to-moderate:
    description: 'The text to moderate.'
    required: true
  retry-count:
    description: 'The number of times to retry the OpenAI API call on failure.'
    required: false
    default: '3'
outputs:
  is-inappropriate:
    description: 'Whether the content was flagged as inappropriate.'
  flagged-categories:
    description: 'A comma-separated list of flagged categories.'
  moderation-results-json:
    description: 'The full JSON response from the OpenAI API.'
runs:
  using: 'node20'
  main: 'dist/index.js'
